spring:
  application:
    name: mall-thirdparty
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    alicloud:
      access-key: LTAI5tBYDeVHVu8sYA65GDDX
      secret-key: CqrSLKsNggwrH2hdDPqlgQDLCrqEZx
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: hzy-mall

server:
  port: 8700

